### ISSUE TITLE
Fix ni.spell.available

### ISSUE THREAD

**Issue by darhanger** [scizzydo/ni#10]
Either I am a crab that does not understand how it works, or it has a bug. As far as I understand inside the function there is **`IsSpellKnown`**. Why then does the program spam spell that I do not know at the moment?

**`if id ~= nil and id ~= 0 and IsSpellKnown(id) then`**

```
-----------------------------------
    ["Shield of Righteousness"] = function()
        if ni.spell.available(61411)
         and ni.spell.isinstant(61411)
         and ni.spell.valid("target", 61411, true, true) then
            ni.spell.cast(61411, "target")
            return true
        end
    end,
-----------------------------------
```

![unknown](https://user-images.githubusercontent.com/22445395/81898403-43fb7080-95c1-11ea-9974-bc8adbc13552.png)

Bulletin says: _"because every check passes"_ 

How it can passes, if ↓ 

![unknown (1)](https://user-images.githubusercontent.com/22445395/81898534-7c9b4a00-95c1-11ea-9b1f-44fe69742407.png)

Yesterday some ppl have problem with new function on pally **`ni.spell.isinstant`** - code did not pass because they had too much ping.

**Comment by scizzydo** [comment]
I don't believe this is an internal issue, but a coding issue. What was your mana when you did the available check? When I did all my testing, the spell failed when I didn't have a shield equipped (not part of the available check) which is checked with IsEquippedItemType("Shields")

Without the shield equipped it'll keep trying to spam the spell, and you will see the output like you have. I can't say it's a bug to the portion of ni as the lua for that check is all pure WoW's lua, nothing introduced from me in your case.
