### ISSUE TITLE
Request ^_^ XOXO

### ISSUE THREAD

**Issue by Lemonadez** [scizzydo/ni#18]
Is it possible to make it easier for party/raid code by adding new function like ni.party and ni.raid
It would lesser than typing for i = 1, #ni.members do and ni.members[i].unit 

Sample would been like this.
![image](https://user-images.githubusercontent.com/19479119/93959561-f63d0480-fd26-11ea-8b51-ceb7bf8184eb.png)

Thanks ^_^.

**Comment by scizzydo** [comment]
This isn’t an issue. When I gave you the suggestion of a pull request it was for you to contribute
