### ISSUE TITLE
Problem with load Data.enc files

### ISSUE THREAD

**Issue by darhanger** [scizzydo/ni#23]
```lua
	require = function(filename)
		if not filename then
			return;
		end
		if not filename:find(".lua") then
			filename = filename..".lua";
		end
		if modules[filename] then
			return modules[filename];
		else
			modules[filename] = ni.functions.require(filename);
			return modules[filename];
		end
	end,
```
Problems in this function) When try enc data files its always return : Data file missing)

**Comment by scizzydo** [comment]
both lua and internal require changes. Darhanger already tested the lua side which needs to remain to his fix by adding the find(".enc") along with me adjusting the internal to see the .enc

**Comment by scizzydo** [comment]
New beta fixes these issues.
