### ISSUE TITLE
RDF Role chose & Leave function problems.

### ISSUE THREAD

**Issue by darhanger** [scizzydo/ni#27]
Floating bug (i think its conflict with some addons) - ppl can't chose role for RDF and sometimes can't leave RDF when ni injected even with turned off profiles. 
This bug found on all popular servers:
• Sirus
• Circle
• Warmane etc.

**Comment by darhanger** [comment]
Almost all have ElvUI but problem not in addons. Same issue with disabled addons. Also not client problem i mean sirus have custom one. And some ppl on sirus have same issue.

**Comment by scizzydo** [comment]
Issue verified no longer present in beta releases
