### ISSUE TITLE
Weird WoW crash.

### ISSUE THREAD

**Issue by darhanger** [scizzydo/ni#37]
Make second "data" file with some garbage like player info / print some stuff etc.

```lua
local data = ni.utils.require("DarhangeR.enc");
local toolkit = ni.utils.require("Toolkit.enc");
```
All work fine without encryption.  But if I encrypt them and call it from profile file its immediately shot down wow.

**Comment by darhanger** [comment]
IDK but seems problem only on my laptop, cuz even on wooded pc all work without problems.

**Comment by darhanger** [comment]
So. Problem with .enc file. 
If path to ni contain russian letters and profiles or data file in .enc its cause instant shutdown wow.

**Comment by scizzydo** [comment]
should be fixed with: https://github.com/scizzydo/ni/tree/v0.0.49

russian letters in path don't cause issue after testing. Profile names cannot have russian however due to the drop down. (When testing with the lua itself it won't allow it)
