### ISSUE TITLE
Functions do not work if you add characters from languages other than English to them.

### ISSUE THREAD

**Issue by Dimonskynew** [scizzydo/ni#40]
The functions do not work if you use a non-English client of the game, and instead of the ID, enter the name of the buff, debuff, or if just letters of a non-English language are entered into any function.
For example:
	 ["Icy Touch"] = function()
	               if not ni.unit.debuff("target", 55095, "player")
			and ni.spell.valid("target", 49909, true, true) 
			and ni.spell.available(49909)
			then
			ni.spell.cast(49909, "target");
			return true;
		end
	end, --Work
	 ["Icy Touch"] = function()
	               if not ni.unit.debuff("target", "Frost Fever, "player")
			and ni.spell.valid("target", 49909, true, true) 
			and ni.spell.available(49909)
			then
			ni.spell.cast(49909, "target");
			return true;
		end
	end, --Work
	 ["Icy Touch"] = function()
	               if not ni.unit.debuff("target", "Озноб", "player")
			and ni.spell.valid("target", 49909, true, true) 
			and ni.spell.available(49909)
			then
			ni.spell.cast(49909, "target");
			return true;
		end
	end, --It does not work correctly, because the function ni.unit.debuff does not work.

Thanks.

**Comment by scizzydo** [comment]
Can you test each line of the function by calling them in game with the arguments your passing. I don't speak any other language than English, and the functions are all normal wow based. Nothing introduced by me. Please see here: https://github.com/scizzydo/ni/blob/beta/addon/Core/unit.lua#L563

**Comment by scizzydo** [comment]
Should be resolved in: https://github.com/scizzydo/ni/tree/v0.0.49

Previous encrypted profiles will need to be rencrypted with new loader also.

Issue seen only when using an actual profile name in russian, and the drop down menu. (This is related to lua and nothing I can do)
