### ISSUE TITLE
Add function to adding stuff to blacklist

### ISSUE THREAD

**Issue by darhanger** [scizzydo/ni#7]
In past Scott help with

local dontdispel = { 34916, 34917, 34919, 48159, 48160, 30404, 30405, 31117, 34438, 35183, 43522, 47841, 47843, 65812, 68154, 68155, 68156, 44461, 55359, 55360, 55361, 55362, 61429, 30108, 34914, 74562, 74792, 70867, 70338, 70405 }
for k, v in pairs(dontdispel) do
    ni.addblacklistdebuff(v)
end

**Comment by scizzydo** [comment]
This isn't an issue, and should be a PR. However I added  debufftoblacklist to the healing table
